name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  CI: true

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/setup-node@v6
      - uses: actions/checkout@v6
      - run: npm install
      - run: npm install eslint@^10
      - run: npm run lint

  coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/setup-node@v6
      - uses: actions/checkout@v6
      - run: npm install
      - run: npm run test:coverage
        env:
          NODE_ENV: cov
      - uses: codecov/codecov-action@v3
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}

  ubuntu:
    needs: [lint, get-lts]
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ${{ fromJson(needs.get-lts.outputs.active) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        name: Node ${{ matrix.node-version }} on ubuntu-latest
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run test

  windows:
    needs: [lint, get-lts]
    permissions:
      contents: read
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: ${{ fromJson(needs.get-lts.outputs.active) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        name: Node.js ${{ matrix.node-version }} on windows-latest
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run test

  get-lts:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - id: get
        uses: msimerson/node-lts-versions@v1
    outputs:
      active: ${{ steps.get.outputs.active }}
      lts: ${{ steps.get.outputs.lts }}
      min: ${{ steps.get.outputs.min }}
