name: publish

on:
  workflow_call:
  push:
    branches:
      - master
    paths:
      - package.json

env:
  CI: true
  node-version: 20

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  publish-npm:
    needs: [ build ]
    runs-on: ubuntu-latest
    environment: npm
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          registry-url: https://registry.npmjs.org/
          scope: "@msimerson"
      - name: rename package with @msimerson scope
        run: node .release/npm/prepend-scope.cjs @msimerson
      - name: publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

  publish-gpr:
    needs: [ build ]
    runs-on: ubuntu-latest
    environment: ghpm
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          registry-url: https://npm.pkg.github.com/
          scope: "@msimerson"
      - name: rename package with @msimerson scope
        run: node .release/npm/prepend-scope.cjs @msimerson
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
