name: publish

on:
  workflow_call:
  push:
    branches:
      - master
    paths:
      - package.json

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/setup-node@v6
      - uses: actions/checkout@v6
      - run: npm install
      - run: npm test

  publish-npm:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment: npm
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true
      - uses: actions/setup-node@v6
        with:
          registry-url: https://registry.npmjs.org/
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

  publish-gpr:
    needs: [build]
    runs-on: ubuntu-latest
    environment: ghpm
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: actions/setup-node@v6
        with:
          registry-url: https://npm.pkg.github.com/
          scope: '@msimerson'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
